services:
  postgres:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    env_file: .dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
