services:
  app:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

volumes:
  postgres_data:
